import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const getCountryFlag = (country: string): string => {
  const flagMap: { [key: string]: string } = {
    'Kosovo': '🇽🇰',
    'Bosnia & Herzegovina': '🇧🇦',
    'Albania': '🇦🇱',
    'North Macedonia': '🇲🇰',
    'Montenegro': '🇲🇪',
    'Serbia': '🇷🇸',
    'Croatia': '🇭🇷',
    'Slovenia': '🇸🇮',
    'Bulgaria': '🇧🇬',
    'Romania': '🇷🇴',
    'Greece': '🇬🇷',
    'Turkey': '🇹🇷',
    'Italy': '🇮🇹',
    'Austria': '🇦🇹',
    'Hungary': '🇭🇺',
    'Slovakia': '🇸🇰',
    'Czech Republic': '🇨🇿',
    'Poland': '🇵🇱',
    'Germany': '🇩🇪',
    'France': '🇫🇷',
    'Spain': '🇪🇸',
    'Portugal': '🇵🇹',
    'United Kingdom': '🇬🇧',
    'Ireland': '🇮🇪',
    'Netherlands': '🇳🇱',
    'Belgium': '🇧🇪',
    'Luxembourg': '🇱🇺',
    'Switzerland': '🇨🇭',
    'Liechtenstein': '🇱🇮',
    'Monaco': '🇲🇨',
    'Andorra': '🇦🇩',
    'San Marino': '🇸🇲',
    'Vatican City': '🇻🇦',
    'Malta': '🇲🇹',
    'Côte d\'Ivoire': '🇨🇮',
    'Cyprus': '🇨🇾',
    'Iceland': '🇮🇸',
    'Norway': '🇳🇴',
    'Sweden': '🇸🇪',
    'Finland': '🇫🇮',
    'Denmark': '🇩🇰',
    'Estonia': '🇪🇪',
    'Latvia': '🇱🇻',
    'Lithuania': '🇱🇹',
    'Belarus': '🇧🇾',
    'Ukraine': '🇺🇦',
    'Moldova': '🇲🇩',
    'Russia': '🇷🇺',
    'Georgia': '🇬🇪',
    'Armenia': '🇦🇲',
    'Azerbaijan': '🇦🇿',
    'Kazakhstan': '🇰🇿',
    'Uzbekistan': '🇺🇿',
    'Turkmenistan': '🇹🇲',
    'Tajikistan': '🇹🇯',
    'Kyrgyzstan': '🇰🇬',
    'Afghanistan': '🇦🇫',
    'Pakistan': '🇵🇰',
    'India': '🇮🇳',
    'Nepal': '🇳🇵',
    'Bhutan': '🇧🇹',
    'Bangladesh': '🇧🇩',
    'Sri Lanka': '🇱🇰',
    'Maldives': '🇲🇻',
    'Myanmar': '🇲🇲',
    'Thailand': '🇹🇭',
    'Laos': '🇱🇦',
    'Vietnam': '🇻🇳',
    'Cambodia': '🇰🇭',
    'Malaysia': '🇲🇾',
    'Singapore': '🇸🇬',
    'Indonesia': '🇮🇩',
    'Brunei': '🇧🇳',
    'Philippines': '🇵🇭',
    'Taiwan': '🇹🇼',
    'China': '🇨🇳',
    'Mongolia': '🇲🇳',
    'North Korea': '🇰🇵',
    'South Korea': '🇰🇷',
    'Japan': '🇯🇵',
    'Canada': '🇨🇦',
    'United States of America': '🇺🇸',
    'Mexico': '🇲🇽',
    'Guatemala': '🇬🇹',
    'Belize': '🇧🇿',
    'El Salvador': '🇸🇻',
    'Honduras': '🇭🇳',
    'Nicaragua': '🇳🇮',
    'Costa Rica': '🇨🇷',
    'Panama': '🇵🇦',
    'Cuba': '🇨🇺',
    'Jamaica': '🇯🇲',
    'Haiti': '🇭🇹',
    'Dominican Republic': '🇩🇴',
    'Puerto Rico': '🇵🇷',
    'Trinidad and Tobago': '🇹🇹',
    'Barbados': '🇧🇧',
    'Saint Lucia': '🇱🇨',
    'Saint Vincent and the Grenadines': '🇻🇨',
    'Grenada': '🇬🇩',
    'Antigua and Barbuda': '🇦🇬',
    'Saint Kitts and Nevis': '🇰🇳',
    'Dominica': '🇩🇲',
    'Brazil': '🇧🇷',
    'Argentina': '🇦🇷',
    'Chile': '🇨🇱',
    'Uruguay': '🇺🇾',
    'Paraguay': '🇵🇾',
    'Bolivia': '🇧🇴',
    'Peru': '🇵🇪',
    'Ecuador': '🇪🇨',
    'Colombia': '🇨🇴',
    'Venezuela': '🇻🇪',
    'Guyana': '🇬🇾',
    'Suriname': '🇸🇷',
    'French Guiana': '🇬🇫',
    'Egypt': '🇪🇬',
    'Libya': '🇱🇾',
    'Tunisia': '🇹🇳',
    'Algeria': '🇩🇿',
    'Morocco': '🇲🇦',
    'Sudan': '🇸🇩',
    'South Sudan': '🇸🇸',
    'Ethiopia': '🇪🇹',
    'Eritrea': '🇪🇷',
    'Djibouti': '🇩🇯',
    'Somalia': '🇸🇴',
    'Kenya': '🇰🇪',
    'Uganda': '🇺🇬',
    'Tanzania': '🇹🇿',
    'Rwanda': '🇷🇼',
    'Burundi': '🇧🇮',
    'Democratic Republic of the Congo': '🇨🇩',
    'Republic of the Congo': '🇨🇬',
    'Central African Republic': '🇨🇫',
    'Chad': '🇹🇩',
    'Cameroon': '🇨🇲',
    'Nigeria': '🇳🇬',
    'Niger': '🇳🇪',
    'Mali': '🇲🇱',
    'Burkina Faso': '🇧🇫',
    'Ghana': '🇬🇭',
    'Togo': '🇹🇬',
    'Benin': '🇧🇯',
    'Senegal': '🇸🇳',
    'Gambia': '🇬🇲',
    'Guinea-Bissau': '🇬🇼',
    'Guinea': '🇬🇳',
    'Sierra Leone': '🇸🇱',
    'Liberia': '🇱🇷',
    'Ivory Coast': '🇨🇮',
    'Mauritania': '🇲🇷',
    'Western Sahara': '🇪🇭',
    'Angola': '🇦🇴',
    'Zambia': '🇿🇲',
    'Zimbabwe': '🇿🇼',
    'Botswana': '🇧🇼',
    'Namibia': '🇳🇦',
    'South Africa': '🇿🇦',
    'Lesotho': '🇱🇸',
    'Swaziland': '🇸🇿',
    'Mozambique': '🇲🇿',
    'Malawi': '🇲🇼',
    'Madagascar': '🇲🇬',
    'Mauritius': '🇲🇺',
    'Seychelles': '🇸🇨',
    'Comoros': '🇰🇲',
    'Mayotte': '🇾🇹',
    'Reunion': '🇷🇪',
    'Australia': '🇦🇺',
    'New Zealand': '🇳🇿',
    'Papua New Guinea': '🇵🇬',
    'Solomon Islands': '🇸🇧',
    'Vanuatu': '🇻🇺',
    'New Caledonia': '🇳🇨',
    'Fiji': '🇫🇯',
    'Samoa': '🇼🇸',
    'Tonga': '🇹🇴',
    'Kiribati': '🇰🇮',
    'Tuvalu': '🇹🇻',
    'Nauru': '🇳🇷',
    'Palau': '🇵🇼',
    'Marshall Islands': '🇲🇭',
    'Micronesia': '🇫🇲',
    'Cook Islands': '🇨🇰',
    'French Polynesia': '🇵🇫',
    'American Samoa': '🇦🇸',
    'Guam': '🇬🇺',
    'Northern Mariana Islands': '🇲🇵',
    'Hawaii': '🇺🇸',
    'Israel': '🇮🇱',
    'Saudi Arabia': '🇸🇦',
    'United Arab Emirates': '🇦🇪',
    'Iran': '🇮🇷'
  };
  return flagMap[country] || '🏳️';
};
